language: python
python:
  - "3.8"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh
  - bash Anaconda3-2020.11-Linux-x86_64.sh -b -p $HOME/Anaconda
  - export PATH="$HOME/Anaconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create -n test-environment python=3.8.5 -f environment.yml
  - sudo apt install git
  - source activate test-environment

script:
  - jupyter nbconvert --to=html --execute ./Code/Task_to_do.ipynb

deploy:
  - provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: cf21243bc0614af83e1729516f01ba7676916877
  repo: https://github.com/leomuskul/JKU-cloud-computing_WS20.git
  local_dir: leomuskul/JKU-cloud-computing_WS20
  email: mykolazelenku@gmail.com
  name: "Mykola Zelenku"
  deployment_file: ./Code/Task_to_do.html
  on:
    branch:
      - main

  # # - echo "# JKU-cloud-computing_WS20" >> read.md
  # - git clone --depth=50 --branch=main https://github.com/leomuskul/JKU-cloud-computing_WS20.git leomuskul/JKU-cloud-computing_WS20
  # - git add ./Code/Task_to_do.html
  # - git commit -m "first commit"
  # # - git remote add origin git@github.com:leomuskul/test-repo.git
  # - git push
notifications:
  email:
    recipients:
      - mykolazelenku@gmail.com
    on_success: always # default: change
    on_failure: always # default: always