language: python
python:
  - "3.8.5"
install:

  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" != "3.8.5" ]]; then
      wget https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh
    fi
  - bash Anaconda3-2020.11-Linux-x86_64.sh -b -p $HOME/Anaconda
  - export PATH="$HOME/Anaconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda env create -n test-environment python=$TRAVIS_PYTHON_VERSION -f environment.yml
  - source activate test-environment

script:
  - py.test